name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ fromJson('{"macos-latest":"macOS","windows-latest":"Windows"}')[matrix.os] }} 3.7 - test
    env:
      MODELKIT_ASSETS_DIR: .local_storage
      MODELKIT_STORAGE_BUCKET: .
      MODELKIT_STORAGE_PREFIX: .remote_storage
      MODELKIT_STORAGE_PROVIDER: local
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: python -m pip install --upgrade nox

      - name: Run Tests
        run: nox -s test

  lint:
    runs-on: ubuntu-latest
    name: Ubuntu 3.7 - lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: python -m pip install --upgrade nox

      - name: Run Lint
        run: nox -s lint

  coverage:
    runs-on: ubuntu-latest
    name: Ubuntu 3.7 - test & coverage
    env:
      MODELKIT_ASSETS_DIR: .local_storage
      MODELKIT_STORAGE_BUCKET: .
      MODELKIT_STORAGE_PREFIX: .remote_storage
      MODELKIT_STORAGE_PROVIDER: local
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python - 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: python -m pip install --upgrade nox

      - name: Run Coverage
        run: nox -s coverage

      - name: Add & Commit Badges
        if: ${{github.ref == 'refs/heads/main'}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/badges
          git diff-index --quiet HEAD || git commit -m "generate badges"
          git push

      - name: Upload Coverage Report
        if: ${{github.ref == 'refs/heads/main'}}
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: docs/coverage
          retention-days: 1
